### PR TITLE
chore: Add Link component to UI kit

### PR DESCRIPTION
**Pull request by ashtonG**
These are the UIKit-related changes for determined-ai/determined#8176 by @gt2345

### CODE REVIEW

**Review by julian-determined-ai — APPROVED** [review]

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
Please add a Link section to the design kit.

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
The External variation from the PRD is missing.

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
The external link [needs to have an indicator](https://fontawesome.com/icons/arrow-up-right-from-square?f=classic&s=solid) that it is an external link.

**Comment by ClaireNeveu** [comment]
@gt2345 It should be a variation of the Link component.

**Comment by gt2345** [comment]
> @gt2345 It should be a variation of the Link component.

@ClaireNeveu 
I think it's better to let user custom the content like 
```
        <Link onClick={() => window.open('https://www.determined.ai/', '_blank')}>
          <Space>
            <Icon name="popout" title="link" />
            External link at a new tab
          </Space>
        </Link>
```
If we add the icon based on a prop such as "external", there is no easy way to discard or change that icon

**Comment by ClaireNeveu** [comment]
@gt2345 We want a standard presentation for external links.

**Review by ClaireNeveu — APPROVED** [review]

**Pull request merged**
